name: tekartik_idb_provider
version: 0.4.0
description: Provider pattern on top of indexeddb
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
  idb_shim: '>=2.0.0'
  collection: any
dev_dependencies:
  process_run: '>=0.10.1'
  test: any
  dev_test: '>=0.13.4'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>2.0.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
dependency_overrides:
  # idb_shim:
  #  path: ../../tekartik/idb_shim.dart/idb_shim